### PR TITLE
`script.js` to `filter.js`

### PR DESCRIPTION
**Pull request by Shluffy**

### CODE REVIEW

**Comment by CodeGuy92** [comment]
But what about the current websites that use this version of the name?

**Comment by Shluffy** [comment]
> But what about the current websites that use this version of the name?

you can make a new branch like `release-7-15-2021` and merge this into that branch and then make a discussion telling people about the upcoming change saying "this change will drop on july 15th, 2021. To get ready for the changed you should be prepared to change the `src` to `filter.js` rather then `script.js`"

**Comment by CodeGuy92** [comment]
> > But what about the current websites that use this version of the name?
> 
> you can make a new branch like `release-7-15-2021` and merge this into that branch and then make a discussion telling people about the upcoming change saying "this change will drop on july 15th, 2021. To get ready for the changed you should be prepared to change the `src` to `filter.js` rather then `script.js`"

And why do we need to change it

**Comment by Shluffy** [comment]
> And why do we need to change it

we should. this names a js script file to be more descriptive, like it would be `filter.html` not `html.html` or `1.html`, `2.html` etc for page names

**Comment by CodeGuy92** [comment]
Sure. But i'll change it when i get a new .com domain too.

**Pull request closed without merging**
