### PR TITLE
CleanREADME

### PR DESCRIPTION
**Pull request by Shluffy**
this adds a clean version of the readme so people who don't want profanity can have a good explanation, but without the profanity

### CODE REVIEW

**Comment by CodeGuy92** [comment]
ok time to review-

**Comment by CodeGuy92** [comment]
This idea is briliant, but it isn't quite descriptive enough so i will remake it. Thanks a lot :D

**Comment by CodeGuy92** [comment]
done

**Comment by ShluffyMonster** [comment]
Okay. Looks good.

**Pull request closed without merging**
